[3scale]
url = "localhost:8000" # 3scale tenant URL

[auth]
url = "localhost:8000" # sso URL
endpoint = "/auth/realms/protocol/openid-connect/token" # path to token
grant_type = "password"
client_id = "676d9abf"
client_secret = "abc123"
username = "testUser"
password = "testUser"